app/models/cliente.py
from flask_login import UserMixin

from app import db


class Clientes(db.Model, UserMixin):
    __tablename__ = 'cliente'
    idCliente = db.Column(db.Integer, primary_key=True)
    nombreCliente = db.Column(db.String(255), nullable=False)
    documentoCliente = db.Column(db.String(255), nullable=False)
    direccion = db.Column(db.String(255), nullable=False)
    telefono = db.Column(db.String(255), nullable=False)
    correo = db.Column(db.String(255), nullable=False)
    contraseña= db.Column(db.String(255), nullable=False)
    vent = db.relationship("Ventas", backref='cliente', lazy=True)


    def get_id(self):
        return str(self.idCliente)

app/routes/cliente_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.cliente import Clientes
from app import db

bp = Blueprint('cliente', __name__)

@bp.route('/cliente')
def index():
    data = Clientes.query.all()
    return render_template('cliente/index.html', data=data)

@bp.route('/Cliente/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombreCliente = request.form['nombreCliente']
        documentoCliente = request.form['documentoCliente']
        direccion    = request.form['direccion']
        telefono     =request.form['telefono']
        correo       = request.form['correo']
        contraseña   = request.form['contraseña']
        new_cliente = Clientes(nombreCliente=nombreCliente, documentoCliente=documentoCliente, direccion=direccion, telefono=telefono, correo=correo,contraseña =contraseña )
        db.session.add(new_cliente)
        db.session.commit()
        
        return render_template('login/login.html')
    return render_template('cliente/add.html')

@bp.route('/cliente/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    cliente = Clientes.query.get_or_404(id)

    if request.method == 'POST':
        cliente.nombreCliente = request.form['nombre']
        cliente.documentoCliente = request.form['documentoCliente']
        cliente.direccion = request.form['direccion']
        cliente.telefono = request.form['telefono']
        cliente.correo = request.form['correo']
        cliente.contraseña= request.form['contraseña']
        db.session.commit()
        return redirect(url_for('cliente.index'))

    return render_template('cliente/edit.html',cliente=cliente)
    

@bp.route('/cliente/delete/<int:id>')
def delete(id):
    Cliente = Clientes.query.get_or_404(id)
    
    db.session.delete(Cliente)
    db.session.commit()

    return redirect(url_for('cliente.index'))

app/templates/cliente/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/boot/css/bootstrap.css') }}">
    <script src="{{ url_for('static', filename='/boot/js/bootstrap.js') }}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='styleCliente.css') }}">
    <style>
        body {
            background: url("{{ url_for('static', filename='/imagenes/florBlanca.jpg') }}") no-repeat center center fixed;
            background-size: cover;
            height: 100vh;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .container {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            width: 300px;
            text-align: center;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
            color: #555;
        }

        input.form-control {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            margin-bottom: 10px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button.btn-primary {
            width: 100%;
            padding: 10px;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            background-color: #a1caba;
        }

        button.btn-info {
            width: 100%;
            padding: 10px;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            background-color: #e1ecc3;
        }
        input{
            margin: 10px;
            width: 400px;
        }
        @media (max-width: 768px) {
            /* Estilos para pantallas más pequeñas */
        }
    </style>
    <title>Inici  Sesion</title>
</head>
<body>
    <div class="container mt-5">

        <h1>Registro</h1>
        <form action="{{ url_for('cliente.add') }}" method="post">
            <div style="display: flex;">
            <div>
            <div class="form-group">
                <label for="nombreCliente">Nombre:</label>
                <input type="text" id="nombreCliente" name="nombreCliente" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="documentoCliente">Documento:</label>
                <input type="text" id="documentoCliente" name="documentoCliente" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="direccion">Dirección:</label>
                <input type="text" id="direccion" name="direccion" class="form-control" required>
            </div>
        </div>
        <div>
            <div class="form-group">
                <label for="telefono">Teléfono:</label>
                <input type="text" id="telefono" name="telefono" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="correo">Correo:</label>
                <input type="text" id="correo" name="correo" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="contraseña">Contraseña:</label>
                <input type="password" id="contraseña" name="contraseña" class="form-control" required>
            </div>
</div>
</div>
            <button type="submit" class="btn btn-primary">Ini</button>
        </form>
    
        
    </div>

app/templates/cliente/edit.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Editar Cliente</title>
</head>
<body>
    <h1>Editar Cliente</h1>
    <form action="{{ url_for('cliente.edit', id=cliente.idCliente) }}" method="post">
        <label for="nombreCliente">Nombre</label>
        <input type="text" id="nombreCliente" name="nombreCliente" value="{{ cliente.nombreCliente }}" required>
        <label for="documentoCliente">Documento</label>
        <input type="text" id="documentoCliente" name="documentoCliente" value="{{ cliente.documentoCliente }}" required>
        <label for="direccion">Direccion</label>
        <input type="text" id="direccion" name="direccion" value="{{ cliente.direccion }}" required>
        <label for="telefono">Telefono</label>
        <input type="text" id="telefono" name="telefono" value="{{ cliente.telefono}}" required>
        <label for="correo">correo</label>
        <input type="text" id="correo" name="correo" value="{{ cliente.correo}}" required>
        <label for="contraseña">Contraseña</label>
        <input type="text" id="contraseña" name="contraseña" value="{{ cliente.contraseña}}" required>
        <button type="submit">Actualizar Cliente</button>
    </form>
</body>
</html>

app/templates/cliente/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='/boot/css/bootstrap.css') }}">
    <script src="{{ url_for('static', filename='/boot/js/bootstrap.js') }}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='styleCliente.css') }}">
    <title>Cliente</title>

    <style>
        body {
            background: url("{{ url_for('static', filename='/imagenes/photos.png') }}") no-repeat center center fixed;
            background-size: cover;
            height: 100vh;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            font-family: Arial, sans-serif;
        }

        .overlay {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            width: 80%;
            max-width: 975px;
            text-align: center;
        }

        h1 {
            color: #494949;
        }

        table {
            width: 100%;
            margin-top: 20px;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            padding: 10px;
            border: 1px solid #dee2e6;
            text-align: left;
        }

        th {
            background-color: #212529;
            color: #ffffff;
        }

        a {
            display: inline-block;
            margin-right: 10px;
            text-decoration: none;
            padding: 8px;
            background-color: #343a40;
            color: #ffffff;
            border-radius: 5px;
        }

        a:hover {
            background-color: #cbd6d2;
        }


        @media (max-width: 768px) {
            /* Estilos para pantallas más pequeñas */
        }
    </style>
</head>

<body>
    <div class="overlay">
        <h1>Lista de Clientes</h1>
        <div style="overflow-x:auto;">
            <table>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Documento</th>
                    <th>Direccion</th>
                    <th>Telefono</th>
                    <th>Correo</th>
                    <th>Contraseña</th>
                    <th>Acciones</th>
                </tr>
                {% for cliente in data %}
                <tr>
                    <td>{{ cliente.idCliente }}</td>
                    <td>{{ cliente.nombreCliente }}</td>
                    <td>{{ cliente.documentoCliente }}</td>
                    <td>{{ cliente.direccion }}</td>
                    <td>{{ cliente.telefono }}</td>
                    <td>{{ cliente.correo }}</td>
                    <td>{{ cliente.contraseña}}</td>
                    <td>
                        <a href="{{ url_for('cliente.edit', id=cliente.idCliente) }}"><i class="bi bi-pencil-square"></i></a>
                        <a href="{{ url_for('cliente.delete', id=cliente.idCliente) }}"><i class="bi bi-archive"></i></a>
                        <!-- Agrega aquí el enlace para eliminar -->
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <a href="{{ url_for('cliente.add') }}">Agregar Cliente</a>
        
        
    </div>
</body>

</html>