app/models/proveedor.py
from app import db


class Proveedores(db.Model):
    __tablename__ = 'proveedor'
    idProveedor = db.Column(db.Integer, primary_key=True)
    nombreProveedor = db.Column(db.String(255), nullable=False)
    documentoProveedor= db.Column(db.String(255), nullable=False)
    celularProveedor = db.Column(db.String(255), nullable=False)
    correo = db.Column(db.String(255), nullable=False)

app/routes/proveedor_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.proveedor import Proveedores
from app import db

bp = Blueprint('proveedor', __name__)

@bp.route('/Proveedores')
def index():
    data = Proveedores.query.all()
    return render_template('proveedor/index.html', data=data)

@bp.route('/proveedor/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombreProveedor= request.form['nombreProveedor']
        documentoProveedor = request.form['documentoProveedor']
        celularProveedor  = request.form['celularProveedor']
        correo       = request.form['correo']
        new_proveedor= Proveedores(nombreProveedor=nombreProveedor , documentoProveedor=documentoProveedor, celularProveedor=celularProveedor, correo= correo)
        db.session.add(new_proveedor)
        db.session.commit()
        
        return redirect(url_for('proveedor.index'))

    return render_template('proveedor/add.html')

@bp.route('/proveedor/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    proveedor = Proveedores.query.get_or_404(id)

    if request.method == 'POST':
        proveedor.nombreProveedor = request.form['nombreProveedor']
        proveedor.documentoProveedor = request.form['documentoProveedor']
        proveedor.celularProveedor = request.form['celularProveedor']
        proveedor.correo = request.form['correo']
    
        db.session.commit()
        return redirect(url_for('proveedor.index'))

    return render_template('proveedor/edit.html',proveedor=proveedor)
    

@bp.route('/proveedor/delete/<int:id>')
def delete(id):
    proveedor = Proveedores.query.get_or_404(id)
    
    db.session.delete(proveedor)
    db.session.commit()

    return redirect(url_for('proveedor.index'))

app/templates/proveedor/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Agregar Proveedor</title>

    <style>
        body {
            background: url("{{ url_for('static', filename='/imagenes/plantas5.webp') }}") no-repeat center center fixed;
            background-size: cover;
            height: 100vh;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .overlay {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            width: 300px;
            text-align: center;
            margin: 20px;
        }

        .container {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            width: 300px;
            text-align: center;
            margin: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
            color: #555;
        }

        input.form-control {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            margin-bottom: 10px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button.btn-primary {
            width: 100%;
            padding: 10px;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            background-color: #a1caba;
        }

        button.btn-info {
            width: 100%;
            padding: 10px;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            background-color: #e1ecc3;
        }

        input {
            margin: 10px;
            width: 90%;
        }
        @media (max-width: 768px) {
            /* Estilos para pantallas más pequeñas */
        }
    </style>
</head>
<body>
    <div class="overlay">
    <h1>Agregar Proveedor</h1>
    <form action="{{ url_for('proveedor.add') }}" method="post">
        <div class="form-group">
        <label for="nombreProveedor">Nombre:</label>
        <input type="text" id="nombreProveedor" name="nombreProveedor" required>
    </div>
    <div class="form-group">
        <label for="documentoProveedor">Documento</label>
        <input type="text" id="documentoProveedor" name="documentoProveedor" required>
    </div>
    <div class="form-group">
        <label for="celularProveedor">Telefono</label>
        <input type="text" id="celularProveedor" name="celularProveedor" required>
    </div>
    <div class="form-group">
        <label for="correo">Correo</label>
        <input type="text" id="correo" name="correo" required>
    </div>
    <div class="form-group">
        <button type="submit">Agregar Provedor</button>
    </form>
</div>
</body>
</html>

app/templates/proveedor/edit.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Editar proveedor</title>

    <style>
        body {
            background: url("{{ url_for('static', filename='/imagenes/plantas5.webp') }}") no-repeat center center fixed;
            background-size: cover;
            height: 100vh;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .overlay {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            width: 300px;
            text-align: center;
            margin: 20px;
        }

        .container {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            width: 300px;
            text-align: center;
            margin: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
            color: #555;
        }

        input.form-control {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            margin-bottom: 10px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button.btn-primary {
            width: 100%;
            padding: 10px;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            background-color: #a1caba;
        }

        button.btn-info {
            width: 100%;
            padding: 10px;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            background-color: #e1ecc3;
        }

        input {
            margin: 10px;
            width: 90%;
        }
        @media (max-width: 768px) {
            /* Estilos para pantallas más pequeñas */
        }
    </style>
</head>
<body>
    <div class="container mt-5">
    <h1>Editar Proveedor</h1>
    <form action="{{ url_for('proveedor.edit', id=proveedor.idProveedor)}}" method="post">
        <div class="form-group">
        <label for="nombreProveedor">Nombre</label>
        <input type="text" id="nombreProveedor" name="nombreProveedor" value="{{ proveedor.nombreProveedor}}" required>
    </div>

    <div class="form-group">
        <label for="documentoCliente">Documento</label>
        <input type="text" id="documentoProveedoor" name="documentoProveedoor" value="{{ proveedor.documentoProveedoor}}" required>
    </div>

    <div class="form-group">
        <label for="celularProveedor">Telefono</label>
        <input type="text" id="celularProveedor" name="celularProveedor" value="{{ proveedor.celularProveedor}}" required>
    </div>

    <div class="form-group">
        <label for="correo">correo</label>
        <input type="text" id="correo" name="correo" value="{{ proveedor.correo}}" required>
    </div>

    <div class="form-group">
        <button type="submit">Actualizar Proveedor</button>
    </div>
    </form>
</div>
</body>
</html>

app/templates/proveedor/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='/boot/css/bootstrap.css') }}">
    <script src="{{ url_for('static', filename='/boot/js/bootstrap.js') }}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <title>Proveedor</title>

    <style>
        body {
            background: url("{{ url_for('static', filename='/imagenes/photos.png') }}") no-repeat center center fixed;
            background-size: cover;
            height: 100vh;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            font-family: Arial, sans-serif;
        }

        .overlay {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            width: 80%;
            max-width: 975px;
            text-align: center;
        }

        h1 {
            color: #494949;
        }

        table {
            width: 100%;
            margin-top: 20px;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            padding: 10px;
            border: 1px solid #dee2e6;
            text-align: left;
        }

        th {
            background-color: #212529;
            color: #ffffff;
        }

        a {
            display: inline-block;
            margin-right: 10px;
            text-decoration: none;
            padding: 8px;
            background-color: #343a40;
            color: #ffffff;
            border-radius: 5px;
        }

        a:hover {
            background-color: #cbd6d2;
        }


        @media (max-width: 768px) {
            /* Estilos para pantallas más pequeñas */
        }
    </style>


</head>

<body>

    <div class="overlay">
        <h1>Lista de Proveedores</h1>
        <div style="overflow-x:auto;">
            <table>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Documento</th>
                    <th>Telefono</th>
                    <th>Correo</th>
                    <th>Acciones</th>
                </tr>
                {% for proveedor in data %}
                <tr>
                    <td>{{ proveedor.idProveedor}}</td>
                    <td>{{ proveedor.nombreProveedor}}</td>
                    <td>{{ proveedor.documentoProveedoor}}</td>
                    <td>{{ proveedor.celularProveedor}}</td>
                    <td>{{ proveedor.correo }}</td>
                    <td>
                        <a href="{{ url_for('proveedor.edit', id=proveedor.idProveedor) }}"><i class="bi bi-pencil-square"></i></a>
                        <a href="{{ url_for('proveedor.delete', id=proveedor.idProveedor) }}"><i class="bi bi-archive"></i></a>

                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <a href="{{ url_for('proveedor.add') }}">Agregar Proveedor</a>
        <br>
        <a href="{{ url_for('administrador.inicio')}}">Inicio</a>
    </div>
</body>

</html>