app/models/detalleVenta.py
from app import db
from sqlalchemy.orm import relationship

class DetalleVentas(db.Model):
    __tablename__ = 'detalleventa'
    idDetalleVenta = db.Column(db.Integer, primary_key=True)
    cantidad =db.Column(db.Integer,nullable=False)
    idProducto = db.Column(db.Integer, db.ForeignKey('producto.idProducto'))
    idVenta= db.Column(db.Integer, db.ForeignKey('venta.idVenta'))
    subTotal =db.Column(db.Integer,nullable=False)

    producto = db.relationship('Productos')

app/routes/detalleVenta_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.detalleVenta import DetalleVentas
from app.models.producto import Productos
from app.models.venta import Ventas
from app.routes.carrito_routes import carrito_compras
from app import db

bp = Blueprint('detalleVenta', __name__)

@bp.route('/detalleVenta')
def index():
    data = DetalleVentas.query.all()
     
    return render_template('detalleVenta/index.html', data=data)
    #return data

@bp.route('/detalleVenta/add/<int:id>', methods=['GET', 'POST'])
def add(id):
    print(id)
    descripcionDV = "Descripcion"
    idVenta = id
    
    for item in carrito_compras.getItems():
        cantidad = item["cantidad"]
        producto = item["producto"]
        new_detalleVenta = DetalleVentas( cantidad = cantidad , idProducto=producto.idProducto,idVenta=idVenta)
        db.session.add(new_detalleVenta)
        db.session.commit()
     #return "Detalle inseratado"
        
        
    factura = Ventas.query.get_or_404(id)
    detalles = DetalleVentas.query.filter_by(idVenta=factura.idVenta)

    return render_template('orquidea/factura.html', factura=factura, detalles=detalles)

    
    ata = Ventas.query.all()
    datas = Productos.query.all()
 

    return render_template('detalleVenta/add.html', data=data, datas=datas)


 #@bp.route('/detalleVenta/add/<int:id>', methods=['GET', 'POST'])
 #def add2():
@bp.route('/detalleVenta/add', methods=['GET', 'POST'])
def add2():
    if request.method == 'POST':
        cantidad  =request.form['cantidad ']
        idProducto =request.form['idProducto']
        idVenta =request.form['idVenta']
        subTotal = request.form['subTotal']
        
        new_detalleVenta = DetalleVentas( cantidad =cantidad ,idProducto=idProducto,idVenta=idVenta,subTotal=subTotal)
        db.session.add(new_detalleVenta)
        db.session.commit()
        
        return redirect(url_for('detalleVenta.index'))
    
    datas = Productos.query.all()
    dat = Ventas.query.all()

    return render_template('detalleVenta/add.html', datas=datas, dat=dat)

@bp.route('/detalleVenta/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    detalleVenta = DetalleVentas.query.get_or_404(id)

    if request.method == 'POST':
        #return "entra al if"
        detalleVenta.cantidad =request.form['cantidad']
        detalleVenta.subTotal =request.form['subTotal']
        detalleVenta.idAdministrador = request.form['idAdministrador']
        detalleVenta.idVenta = request.form['idVenta']
        
        db.session.commit()
        
        return redirect(url_for('detalleVenta.index'))

    return render_template('detalleVenta/edit.html', detalleVenta=detalleVenta)

@bp.route('/detalleVenta/delete/<int:id>')
def delete(id):
   detalleVenta = DetalleVentas.query.get_or_404(id)
   
   db.session.delete(detalleVenta)
   db.session.commit() 
    

   return redirect(url_for('detalleVenta.index'))

app/templates/detalleVenta/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Agregar Detalle Venta</title>
</head>
<body>
    <h1>Agregar Detalle Venta</h1>
    <form action="{{ url_for('detalleVenta.add') }}" method="post">
        <label for="cantidad">Cantidad</label>
        <input type="text" id="cantidad" name="cantidad" required>
        <label for="subTotal">SubTotal</label>
        <input type="int" id="subTotal" name="cantidad" required>

        <label for="producto"> ID Producto:</label>

        <select id="idProducto" name="idProducto">
            {% for producto in datas %}
                <option value="{{producto.idProducto}}">{{producto.nombreProducto}}</option>
            {% endfor %}
        </select>

        <label for="venta"> ID Venta:</label>

        <select id="idVenta" name="idVenta">
            {% for venta in data %}
                <option value="{{ venta.idVenta}}">{{venta.descripcionVenta}}</option>
            {% endfor %}
        </select>
        <button type="submit">Agregar Detalle Venta</button>
    </form>
</body>
</html>

app/templates/detalleVenta/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Editar Detalle Venta</title>
</head>
<body>
    <h1>Editar Detalle Venta</h1>
    <form action="{{ url_for('detalleVenta.edit', id=detalleVenta.idDetalleVenya) }}" method="post">
        <label for="cantidad">Cantidad</label>
        <input type="text" id="cantidad" name="cantidad" value="{{detalleVenta.cantidad}}" required>
        <label for="subTotal">SubTotal</label>
        <input type="int" id="subTotal" name="subTotal" value="{{detalleVenta.subTotal}}" required>
        <label for="producto">ID Producto</label>
        <input type="text" id="producto" name="producto" value="{{ detalleVenta.producto}}" required>
        <label for="venta">ID Venta</label>
        <input type="text" id=""venta name="venta" value="{{ detalleVenta.venta}}" required>
        <button type="submit">Actualizar  Detalle Venta</button>
    </form>
</body>
</html>

app/templates/detalleVenta/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title> Detalle Venta</title>

    <style>
        body {
            background: url("{{ url_for('static', filename='/imagenes/photos.png') }}") no-repeat center center fixed;
            background-size: cover;
            height: 100vh;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            font-family: Arial, sans-serif;
        }

        .overlay {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            width: 80%;
            max-width: 975px;
            text-align: center;
        }

        h1 {
            color: #494949;
        }

        table {
            width: 100%;
            margin-top: 20px;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            padding: 10px;
            border: 1px solid #dee2e6;
            text-align: left;
        }

        th {
            background-color: #212529;
            color: #ffffff;
        }

        a {
            display: inline-block;
            margin-right: 10px;
            text-decoration: none;
            padding: 8px;
            background-color: #343a40;
            color: #ffffff;
            border-radius: 5px;
        }

        a:hover {
            background-color: #cbd6d2;
        }


        @media (max-width: 768px) {
            /* Estilos para pantallas más pequeñas */
        }
    </style>
</head>

<body>
    <div class="overlay">
    <h1>Lista de Detalle Venta</h1>
    <div style="overflow-x:auto;">
    <table>
        <tr>
            <th>ID</th>
            <th>Cantidad</th>
            <th>ID Producto</th>
            <th>ID Venta</th>
            <th>Acciones</th>
            <th>SubTotal</th>
        </tr>
        {% for detalleVenta in data %}
        <tr>
            <td>{{ detalleVenta.idDetalleVenta}}</td>
            <td>{{ detalleVenta.cantidad}}</td>
            <td>{{ detalleVenta.subTotal}}</td>
            <td>{{ detalleVenta.idProducto }}</td>
            <td>{{ detalleVenta.idCompra }}</td>
            <td>
                <!-- <a href="{{ url_for('detalleVenta.edit', id=detalleVenta.idDetalleVenta) }}">Editar</a>
                    <a href="{{ url_for('detalleVenta.delete', id=detalleVenta.idDetalleVenta) }}">Eliminar</a>                 
                    Agrega aquí el enlace para eliminar -->
            </td>
        </tr>
        {% endfor %}
    </table>

</div>
<a href="{{ url_for('administrador.inicio')}}">Inicio</a>
</div>
</body>

</html>