app/models/producto.py
from app import db


class Productos(db.Model):
    __tablename__ = 'producto'
    idProducto = db.Column(db.Integer, primary_key=True)
    nombreProducto = db.Column(db.String(255), nullable=False)
    precioProductocompra= db.Column(db.Integer, nullable=False)
    precioProductoventa= db.Column(db.Integer, nullable=False)
    imagen = db.Column(db.String(255), nullable=True)
    vent = db.relationship("Ventas", secondary="detalleventa", back_populates="productos", single_parent=False)

app/routes/carrito_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from sqlalchemy import func
from app.models.producto import Productos
from app.models.carrito import Carritos
from app.models.venta import Ventas
from app.models.detalleVenta import DetalleVentas
from flask_login import current_user, login_required
from app import db



bp = Blueprint('carritos', __name__)
carrito_compras = Carritos()

@bp.route('/ListarCarrito')
def listar():
    items = carrito_compras.getItems()
    return render_template('producto/listar.html', items=items)

@bp.route('/ListarProductos')
def index():
    productos = carrito_compras
    return render_template('index.html', productos=productos)

@bp.route('/agregar/<int:id>', methods=['POST'])
def agregar_al_carrito(id):
    cantidad = int(request.form.get('cantidad', 1))
   
    #return redirect(url_for('producto.index'))
    items = carrito_compras.getItems()
    for item in items:
        if item['producto'].idProducto == id:
            item['cantidad'] += cantidad
            return redirect(url_for('producto.index1'))
    carrito_compras.agregar_producto(id, cantidad)
    return redirect(url_for("producto.index1"))
    #return "Entra a agregar corrito"



@bp.route('/eliminar/<int:id>', methods=['POST','GET'])
def eliminarItem1(id):
    Items = carrito_compras.getItems()
    for item in Items:
        if  item['producto'].idProducto ==id:
            carrito_compras.eliminarItem(item)
    return render_template('producto/listar.html', items=Items)
    
    #return "Entra a agregar corrito"

@bp.route('/eliminar/<int:id>', methods=['POST','GET'])
def eliminarItem(id):
    items = carrito_compras.getItems()
    for item in items:
        if item['producto'].idProducto== id:
            carrito_compras.eliminarItem(item)
            return redirect(url_for('carritos.listar'))  # Redirigir a la vista del carrito
    return redirect(url_for('carritos.listar'))  # Redirigir a la vista del carrito

@bp.route('/realizar_compra')
@login_required
def realizar_compra():
    total = carrito_compras.calcular_total()
    new_venta = Ventas(fechaV=func.now() ,descripcionVenta="Venta de prodcutos", idCliente=current_user.idCliente, totalV=total)
    db.session.add(new_venta)
    db.session.commit()

    factura =carrito_compras.getItems()

    for producto in factura:
        producto2 = producto['producto']
        detalles = DetalleVentas(cantidad=producto['cantidad'], subTotal=producto2.precioProductoventa, idVenta=new_venta.idVenta, idProducto=producto2.idProducto)
        db.session.add(detalles)

    db.session.commit()
    detalle = DetalleVentas.query.filter_by(idVenta=new_venta.idVenta).all()

    return render_template('carrito/realizar_compra.html', detalles=detalle,new_venta=new_venta)


    #return redirect(url_for('venta.add'))

@bp.route('/generar_compra', methods=['POST'])
def generar_factura():
    total = carrito_compras.calcular_total()
    return redirect(url_for('venta.add'))
    #return render_template('carrito/factura.html', total=total)

@bp.route('/itemscarrito', methods=['GET', 'POST'])
def tCarrito():
    a = carrito_compras.tamañoD()
    print("Entra a carrito rutas", a)
    return f"Entra a carrito {carrito_compras.tamañoD()}"

@bp.route('/vaciar_carrito',methods=["POST"])
def vaciar_carrito():
    carrito_compras.vaciarcarrito()
    return render_template('producto/listar.html')
    

app/routes/producto_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify,flash
from flask_login import login_required
from app.models.producto import Productos
from app.routes.carrito_routes import carrito_compras
from app import db
import os
from flask_login import current_user


bp = Blueprint('producto', __name__)

@bp.route('/producto2')
def index():
    data = Productos.query.all()
    return render_template('producto/index.html', data=data, t =carrito_compras.tamañoD())

@bp.route('/producto')
@login_required
def index1():
    data = Productos.query.all()
    return render_template('principal/index.html', data=data)

@bp.route('/producto1')
def vista():
    data = Productos.query.all()
    return render_template('principal/index1.html', data=data)

@bp.route('/produ')
def ideales():
    data = Productos.query.all()
    return render_template('servicios/index.html', data=data)

@bp.route('/producto/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombreProducto = request.form['nombreProducto']
        precioProductocompra = request.form['precioProductocompra']
        precioProductoventa    = request.form['precioProductoventa']
        imagen = request.files['imagenProducto']
        
        new_producto = Productos(nombreProducto=nombreProducto, precioProductocompra=precioProductocompra, precioProductoventa=precioProductoventa, imagen=imagen.filename)
       
        guardarImagen(imagen)
        
        

        db.session.add(new_producto)
        db.session.commit()
        


        return redirect(url_for('producto.index'))

    return render_template('producto/add.html')

@bp.route('/producto/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    producto = Productos.query.get_or_404(id)

    if request.method == 'POST':
        producto.nombreProducto = request.form['nombreProducto']
        producto.precioProductocompra = request.form['productoPreciocompra']
        producto.precioProductoventa= request.form['productoPrecioventa']
        


        db.session.commit()
        return redirect(url_for('producto.index'))

    return render_template('producto/edit.html',producto=producto)
    

@bp.route('/producto/delete/<int:id>')
def delete(id):
    producto= Productos.query.get_or_404(id)
    
    try:
        db.session.delete(producto)
        db.session.commit()
    except Exception as error:
        db.session.rollback()
        flash('el producto no se puede eliminar', 'danger')
    
    return redirect(url_for('producto.index'))


def guardarImagen(imagen):
    from run import app
    carpetaDestino = os.path.join(app.root_path, "static" ,"imagenes")
    imagen.save(os.path.join(carpetaDestino, imagen.filename))




def eliminar(idProducto):
    from run import app
    producto = producto.query.get_or_404(idProducto)
    ruta_imagen = os.path.join(app.root_path, "static" ,"imagenes", producto.imagen)

    if os.path.exists(ruta_imagen):
        os.remove(ruta_imagen)

app/templates/producto/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Agregar Producto</title>

    <style>
        body {
            background: url("{{ url_for('static', filename='/imagenes/plantas5.webp') }}") no-repeat center center fixed;
            background-size: cover;
            height: 100vh;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .overlay {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            width: 300px;
            text-align: center;
            margin: 20px;
        }

        .container {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            width: 300px;
            text-align: center;
            margin: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
            color: #555;
        }

        input.form-control {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            margin-bottom: 10px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button.btn-primary {
            width: 100%;
            padding: 10px;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            background-color: #a1caba;
        }

        button.btn-info {
            width: 100%;
            padding: 10px;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            background-color: #e1ecc3;
        }

        input {
            margin: 10px;
            width: 90%;
        }
        @media (max-width: 768px) {
            /* Estilos para pantallas más pequeñas */
        }
    </style>
</head>
<body>
    <div class="overlay">
    <h1>Agregar Producto</h1>
    <form action="{{ url_for('producto.add') }}" method="post" enctype="multipart/form-data">
        <div class="form-group">
        <label for="nombreProducto">Nombre:</label>
        <input type="text" id="nombreProducto" name="nombreProducto" required>
    </div>
    <div class="form-group">
        <label for="precioProductocompra">Precio Compra</label>
        <input type="text" id="precioProductocompra" name="precioProductocompra" required>
    </div>
    <div class="form-group">
        <label for="precioProductoventa">Precio Venta</label>
        <input type="text" id="precioProductoventa" name="precioProductoventa" required>
    </div>
    <div class="form-group">
        <input type="file" accept=".png, .jpg, jpng" name="imagenProducto">
        
        <button type="submit">Agregar Producto</button>
    </form>
</div>
</body>
</html>

app/templates/producto/edit.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Editar Producto</title>

    <style>
        body {
            background: url("{{ url_for('static', filename='/imagenes/plantas5.webp') }}") no-repeat center center fixed;
            background-size: cover;
            height: 100vh;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .overlay {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            width: 300px;
            text-align: center;
            margin: 20px;
        }

        

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
            color: #555;
        }

        input.form-control {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            margin-bottom: 10px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button.btn-primary {
            width: 100%;
            padding: 10px;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            background-color: #a1caba;
        }

        button.btn-info {
            width: 100%;
            padding: 10px;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            background-color: #e1ecc3;
        }

        input {
            margin: 10px;
            width: 90%;
        }
        @media (max-width: 768px) {
            /* Estilos para pantallas más pequeñas */
        }
    </style>
</head>
<body>
    <div class="overlay">
    <h1>Editar Producto</h1>
    <form action="{{ url_for('producto.edit', id=producto.idProducto) }}" method="post">
        <div class="form-group">
        <label for="nombreProducto">Nombre</label>
        <input type="text" id="nombreProducto" name="nombreProducto" value="{{ producto.nombreProducto }}" required>
        <label for="precioProductocompra">Precio Compra</label>
        <input type="text" id="precioProductocompra" name="precioProductocompra" value="{{ producto.precioProductocompra }}" required>
        <label for="precioProductoventa">Precio VEnta</label>
        <input type="text" id="precioProductoventa" name="precioProductoventa" value="{{ producto.precioProductoventa }}" required>
        <button type="submit">Actualizar Producto</button>
    </form>
</div>
</div>
</body>
</html>

app/templates/producto/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='/boot/css/bootstrap.css') }}">
    <script src="{{ url_for('static', filename='/boot/js/bootstrap.js') }}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
   
    <title>Producto</title>
    <style>
    body {
        background: url("{{ url_for('static', filename='/imagenes/photos.png') }}") no-repeat center center fixed;
        background-size: cover;
        height: 100vh;
        margin: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        font-family: Arial, sans-serif;
    }

    .overlay {
        background: rgba(255, 255, 255, 0.8);
        padding: 20px;
        border-radius: 10px;
        width: 80%;
        max-width: 975px;
        text-align: center;
    }

    h1 {
        color: #494949;
    }

    table {
        width: 100%;
        margin-top: 20px;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    th,
    td {
        padding: 10px;
        border: 1px solid #dee2e6;
        text-align: left;
    }

    th {
        background-color: #212529;
        color: #ffffff;
    }

    a {
        display: inline-block;
        margin-right: 10px;
        text-decoration: none;
        padding: 8px;
        background-color: #343a40;
        color: #ffffff;
        border-radius: 5px;
    }

    a:hover {
        background-color: #cbd6d2;
    }


    @media (max-width: 768px) {
        /* Estilos para pantallas más pequeñas */
    }
</style>
</head>

<body>
    <div class="overlay">
    
    <div style="overflow-x:auto;">
        <h1>Lista de Producto</h1>
    <table>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Precio Compra</th>
            <th>Precio Venta</th>
            <th>Acciones</th>
        </tr>
        {% for producto in data %}
        <tr>
            <td>{{ producto.idProducto }}</td>
            <td>{{ producto.nombreProducto }}</td>
            <td>{{ producto.precioProductocompra }}</td>
            <td>{{ producto.precioProductoventa }}</td>
            <td>
                

                <a href="{{ url_for('producto.edit', id=producto.idProducto) }}"><i class="bi bi-pencil-square"></i></a>
                <a href="{{ url_for('producto.delete', id=producto.idProducto) }}"><i class="bi bi-archive"></i></a>

            </td>
        </tr>
        {% endfor %}
    </table>
</div>
    <a href="{{ url_for('producto.add') }}"> Agregar Producto</a>
    <br>
    <a href="{{ url_for('administrador.inicio')}}">Inicio</a>
</div>
</body>

</html>

app/templates/producto/listar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='/boot/css/bootstrap.css') }}">
    <script src="{{ url_for('static', filename='/boot/js/bootstrap.js') }}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <title>Carrito</title>
    <style>
        body {
            background: url("{{ url_for('static', filename='/imagenes/photos.png') }}") no-repeat center center fixed;
            background-size: cover;
            height: 100vh;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            font-family: Arial, sans-serif;
        }

        .overlay {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            width: 80%;
            max-width: 975px;
            text-align: center;
        }

        h1 {
            color: #494949;
        }

        table {
            width: 100%;
            margin-top: 20px;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            padding: 10px;
            border: 1px solid #dee2e6;
            text-align: left;
        }

        th {
            background-color: #212529;
            color: #ffffff;
        }

        a {
            display: inline-block;
            margin-right: 10px;
            text-decoration: none;
            padding: 8px;
            background-color: #343a40;
            color: #ffffff;
            border-radius: 5px;
        }

        a:hover {
            background-color: #cbd6d2;
        }


        @media (max-width: 768px) {
            /* Estilos para pantallas más pequeñas */
        }
    </style>

</head>

<body>
<div class="container">
    <div class="invoice">

    <h1 class="mt-3 mb-4">Carrito de Compras</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Producto</th>
                <th scope="col">Precio</th>
                <th scope="col">Cantidad</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
                <tr>
                    <td>{{ item['producto'].nombreProducto }}</td>
                    <td>{{ item['producto'].precioProductoventa }}</td>
                    <td>{{ item['cantidad'] }}</td>
                    <td>
                        <form action="{{ url_for('carritos.eliminarItem', id=item['producto'].idProducto) }}" method="post">
                            <button type="submit" class="btn btn-danger">Eliminar Producto</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <form action="{{ url_for('carritos.vaciar_carrito') }}" method="post" class="mb-3">
        <button type="submit" class="btn btn-group">Vaciar Carrito</button>
    </form>

    <a href="{{ url_for('carritos.realizar_compra') }}">Generar Factura</a>
    
    <a href="{{ url_for('administrador.inicio')}}">Inicio</a>
</div>
</div>
</body>


</html>